// playground/react/components/ProductCard.jsx
// A component reused across the products grid — its host elements stamp to
// ProductCard.jsx, and its many instances exercise the occurrence-index id.
export default function ProductCard({ product }) {
  return (
    <div className="product">
      <div className="muted">{product.category}</div>
      <h3>{product.name}</h3>
      <div className="price">${product.price}</div>
    </div>
  );
}

// playground/svelte/components/ProductCard.svelte
<!-- Reused across the products grid — its host elements stamp to
     ProductCard.svelte, and its many instances exercise the occurrence-index id. -->
<script>
  let { product } = $props();
</script>

<div class="product">
  <div class="muted">{product.category}</div>
  <h3>{product.name}</h3>
  <div class="price">${product.price}</div>
</div>
