// playground/react/App.jsx
import { useRoute, Link } from "./router.jsx";
import Home from "./pages/Home.jsx";
import Products from "./pages/Products.jsx";
import About from "./pages/About.jsx";

export default function App() {
  const route = useRoute();

  let page;
  if (route.path === "/") page = <Home />;
  else if (route.path === "/products") page = <Products query={route.query} />;
  else if (route.path === "/about") page = <About />;
  else
    page = (
      <div className="section">
        <h2>404</h2>
        <p className="muted">No page at {route.path}</p>
        <Link to="/">← Back home</Link>
      </div>
    );

  return (
    <div>
      <header className="nav">
        <div className="nav-inner">
          <span className="brand">◎ Spotnote</span>
          <nav className="nav-links">
            <Link to="/">Home</Link>
            <Link to="/products?category=all&sort=name">Products</Link>
            <Link to="/about">About</Link>
          </nav>
        </div>
      </header>
      <main className="page">{page}</main>
      <footer className="footer">Spotnote playground · React + Vite</footer>
    </div>
  );
}

// playground/vue/App.vue
<script setup>
import { computed } from "vue";
import { route } from "./router.js";
import AppLink from "./components/AppLink.vue";
import Home from "./pages/Home.vue";
import Products from "./pages/Products.vue";
import About from "./pages/About.vue";

// Pages read the shared `route` themselves, so no props to thread through.
const page = computed(() => {
  const p = route.value.path;
  if (p === "/") return Home;
  if (p === "/products") return Products;
  if (p === "/about") return About;
  return null;
});
</script>

<template>
  <div>
    <header class="nav">
      <div class="nav-inner">
        <span class="brand">◎ Spotnote</span>
        <nav class="nav-links">
          <AppLink to="/">Home</AppLink>
          <AppLink to="/products?category=all&sort=name">Products</AppLink>
          <AppLink to="/about">About</AppLink>
        </nav>
      </div>
    </header>

    <main class="page">
      <component :is="page" v-if="page" />
      <div v-else class="section">
        <h2>404</h2>
        <p class="muted">No page at {{ route.path }}</p>
        <AppLink to="/">← Back home</AppLink>
      </div>
    </main>

    <footer class="footer">Spotnote playground · Vue + Vite</footer>
  </div>
</template>
